Add files via upload
Fall23csc509/CodeVillage pull request #100
Opened 2023-11-14 00:34 UTC by DhillonTaran

for issue #35

2023-11-14 00:39 UTC, liamhyde02 requested changes
this needs to implement the EntityParsingStep interface and add stuff to the Singleton, not return a static set

2023-11-15 23:20 UTC, liamhyde02 requested changes

2023-11-15 23:20 UTC, liamhyde02 commented on src/main/java/org/codevillage/InheritanceParsingStep.java
> +        JavaEntity entity = next.construct(builder, declaration);
you don't need to parse the entity here, just put everything into the builder

2023-11-15 23:20 UTC, liamhyde02 commented on src/main/java/org/codevillage/InheritanceParsingStep.java
> +        return entity;
need to return next.construct here

2023-11-15 23:20 UTC, buk0vec requested changes
This is supposed to address issue #35

2023-11-15 23:20 UTC, buk0vec commented on src/main/java/org/codevillage/InheritanceParsingStep.java
> +        JavaEntity entity = next.construct(builder, declaration);
Call this at the end of the function!

2023-11-15 23:20 UTC, buk0vec commented on src/main/java/org/codevillage/InheritanceParsingStep.java
> +    private Set<String> getAssociatedClassNames(Object entity) {
Isn't your task to just get the parent class of the ClassOrInterfaceDeclaration if it has one? Kind of confused on why all this logic is needed

2023-11-15 23:20 UTC, buk0vec commented on src/main/java/org/codevillage/InheritanceParsingStep.java
> +        JavaEntity entity = next.construct(builder, declaration);
Otherwise it will run out of order. Just look at the other steps

2023-11-16 00:25 UTC, buk0vec approved these changes
lgtm

2023-11-16 00:27 UTC, liamhyde02 approved these changes
lgtm

2023-11-16 00:27 UTC, merged