Add files via upload
Fall23csc509/CodeVillage pull request #101
Opened 2023-11-14 00:36 UTC by DhillonTaran

for issue #36

2023-11-14 00:42 UTC, liamhyde02 requested changes
Same as other prs, need to extend EntityParsingStep and use the EntityBuilder passed through the chain of responsibility

2023-11-14 00:44 UTC, khoa-l commented
You're not merging into mainline?

2023-11-15 18:39 UTC, buk0vec requested changes
Please rewrite to actually pull compositions from the CompilationUnit!

2023-11-15 18:39 UTC, buk0vec commented on src/main/java/org/codevillage/CompositionParsingStep.java
> +        JavaEntity entity = builder.build();
We don't call this until the last step

2023-11-15 18:39 UTC, buk0vec commented on src/main/java/org/codevillage/CompositionParsingStep.java
> +    private List<String> getCompositionClassNames(JavaEntity entity) {
This... doesn't work. You are getting the *literal class instance* of the JavaEntity and iterating through it. All these steps work around using the CompilationUnit that is passed in to determine things about the JavaEntity that we are trying to build. Please refer to how the other EntityParsingSteps work to see what I mean, the pattern will be similar to LOCParsingStep

2023-11-15 18:39 UTC, buk0vec commented on src/main/java/org/codevillage/CompositionParsingStep.java
> +        return entity;
Not needed

2023-11-15 18:41 UTC, buk0vec commented on src/main/java/org/codevillage/CompositionParsingStep.java
> +    private List<String> getCompositionClassNames(JavaEntity entity) {
To clarify, JavaEntity is just a data class. We are calling methods on the builder as we find things out about the entity that we are building from the CompilationUnit (ex. name, realizations, etc). I'd recommend syncing-up with the rest of the repository and looking at the UML to see how everything works together.

2023-11-15 23:15 UTC, buk0vec approved these changes
lgtm, assuming you've tested these btw

2023-11-15 23:42 UTC, buk0vec approved these changes
lgtm idk i hope it works

2023-11-16 00:14 UTC, liamhyde02 approved these changes
lgtm

2023-11-16 00:14 UTC, merged